sudo: required
language: python

matrix:
  include:
    - os: linux
      dist: trusty
      python: 2.7
    - os: linux
      dist: trusty
      python: 3.4

virtualenv:
  system_site_packages: true

# whitelist
branches:
  only:
    - master

# command to install dependencies
before_install:
  - sudo apt update
  - if [ $TRAVIS_PYTHON_VERSION == "2.7" ]; then sudo apt install python-numpy python-scipy python-matplotlib python-qt4 python-h5py; fi
  - if [ $TRAVIS_PYTHON_VERSION == "3.4" ]; then sudo apt install python3-numpy python3-scipy python3-matplotlib python3-pyqt4 python3-h5py; fi
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: 
  - if [ $TRAVIS_PYTHON_VERSION == "3.4" ]; then 2to3-3.4 -w scripts/quicknxs quicknxs tests test_all.py; fi
# command to run tests
script: 
  - if [ $TRAVIS_PYTHON_VERSION == "2.7" ]; then python -m unittest test_all; fi
  - if [ $TRAVIS_PYTHON_VERSION == "3.4" ]; then python -m unittest tests.qreduce_test tests.qcalc_test tests.qio_test; fi

